<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"
  xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>XML Sitemap — MD. Shinha Sarder</title>
        <style>
          *{box-sizing:border-box;margin:0;padding:0}
          body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;background:#f1f3f6;color:#1f2937;line-height:1.5}
          header{background:linear-gradient(135deg,#0a2540,#13355f);color:#fff;padding:48px 20px;text-align:center}
          header h1{font-size:34px;font-weight:700;margin-bottom:8px}
          header p{font-size:14px;opacity:.85;margin:2px 0}
          .wrap{max-width:1180px;margin:-30px auto 40px;padding:0 20px}
          .card{background:#fff;border-radius:10px;overflow:hidden;box-shadow:0 6px 24px rgba(15,42,90,.08)}
          table{width:100%;border-collapse:collapse;font-size:14px}
          thead th{background:#0e5599;color:#fff;text-align:left;padding:14px 18px;font-weight:600;font-size:13px;letter-spacing:.3px}
          tbody td{padding:13px 18px;border-bottom:1px solid #eef2f7;vertical-align:middle}
          tbody tr:nth-child(even){background:#f8fafc}
          tbody tr:hover{background:#eef6ff}
          a{color:#0e5599;text-decoration:none}
          a:hover{text-decoration:underline}
          .muted{color:#64748b;font-size:12px}
          footer{text-align:center;padding:20px;color:#64748b;font-size:12px}
          .pill{display:inline-block;background:#e6f0fb;color:#0e5599;padding:2px 8px;border-radius:999px;font-size:11px;margin-left:6px}
        </style>
      </head>
      <body>
        <header>
          <h1>XML Sitemap</h1>
          <p>Generated by SiteSEO</p>
          <xsl:if test="s:sitemapindex">
            <p>This XML Sitemap Index file contains <xsl:value-of select="count(s:sitemapindex/s:sitemap)"/> sitemaps</p>
          </xsl:if>
          <xsl:if test="s:urlset">
            <p>This XML Sitemap contains <xsl:value-of select="count(s:urlset/s:url)"/> URLs</p>
          </xsl:if>
        </header>
        <div class="wrap">
          <div class="card">
            <xsl:if test="s:sitemapindex">
              <table>
                <thead><tr><th>URL</th><th style="width:280px">Last Modified</th></tr></thead>
                <tbody>
                  <xsl:for-each select="s:sitemapindex/s:sitemap">
                    <tr>
                      <td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
                      <td class="muted"><xsl:value-of select="s:lastmod"/></td>
                    </tr>
                  </xsl:for-each>
                </tbody>
              </table>
            </xsl:if>
            <xsl:if test="s:urlset">
              <table>
                <thead><tr><th>URL</th><th style="width:160px">Images</th><th style="width:220px">Last Modified</th></tr></thead>
                <tbody>
                  <xsl:for-each select="s:urlset/s:url">
                    <tr>
                      <td>
                        <a href="{s:loc}"><xsl:value-of select="s:loc"/></a>
                        <xsl:if test="news:news"><span class="pill">news</span></xsl:if>
                        <xsl:if test="video:video"><span class="pill">video</span></xsl:if>
                      </td>
                      <td class="muted"><xsl:value-of select="count(image:image)"/></td>
                      <td class="muted"><xsl:value-of select="s:lastmod"/></td>
                    </tr>
                  </xsl:for-each>
                </tbody>
              </table>
            </xsl:if>
          </div>
          <footer>© MD. Shinha Sarder · mdshinhasarder.com</footer>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
